test:
    meson test -C build
bench:
    meson test --benchmark -C build -t 0
setup:
    meson setup build --buildtype=debug -Db_lundef=false -Db_sanitize=address,undefined --reconfigure
setup_no_san:
    meson setup build --reconfigure
